# Generated by Django 6.0.2 on 2026-03-02 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import src.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", src.core.fields.ULIDField(primary_key=True, serialize=False)),
                ("key_hash", models.CharField(db_index=True, max_length=64)),
                ("key_prefix", models.CharField(max_length=8)),
                ("label", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "keys_apikey",
                "ordering": ["-created_at"],
            },
        ),
    ]
