# Generated by Django 6.0.2 on 2026-03-01 23:43

import django.db.models.deletion
from django.db import migrations, models

import src.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", src.core.fields.ULIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("given_name", models.CharField(blank=True, max_length=255, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=255, null=True)),
                ("surname", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "persons_person",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonName",
            fields=[
                ("id", src.core.fields.ULIDField(primary_key=True, serialize=False)),
                (
                    "name_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("birth", "Birth"),
                            ("maiden", "Maiden"),
                            ("married", "Married"),
                            ("former", "Former"),
                            ("alias", "Alias"),
                            ("nickname", "Nickname"),
                            ("professional", "Professional"),
                            ("transliteration", "Transliteration"),
                            ("abbreviation", "Abbreviation"),
                            ("misspelling", "Misspelling"),
                        ],
                        max_length=30,
                    ),
                ),
                ("full_name", models.CharField(max_length=500)),
                ("given_name", models.CharField(blank=True, max_length=255, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=255, null=True)),
                ("surname", models.CharField(blank=True, max_length=255, null=True)),
                ("prefix", models.CharField(blank=True, max_length=50, null=True)),
                ("suffix", models.CharField(blank=True, max_length=50, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("source", models.CharField(max_length=100)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "db_table": "persons_personname",
                "ordering": ["-is_primary", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("person",),
                        name="unique_primary_per_person",
                    )
                ],
            },
        ),
    ]
