# Generated by Django 6.0.2 on 2026-03-02 04:45

import django.db.models.deletion
from django.db import migrations, models

import src.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonAttribute",
            fields=[
                ("id", src.core.fields.ULIDField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=200)),
                ("value", models.TextField()),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "db_table": "persons_personattribute",
                "ordering": ["-created_at"],
            },
        ),
    ]
