# Generated by Django 6.0.2 on 2026-03-02 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0002_personattribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personattribute",
            name="confidence",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
    ]
