# Generated by Django 6.0.2 on 2026-03-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_personattribute_confidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("display", models.CharField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "persons_socialplatform",
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.AddField(
            model_name="personattribute",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personattribute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="personattribute",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("url", "URL"),
                    ("platform_url", "Platform URL"),
                    ("location", "Location"),
                    ("date", "Date"),
                ],
                db_index=True,
                default="text",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AttributeLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_type", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("display", models.CharField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "persons_attributelabel",
                "ordering": ["value_type", "sort_order", "slug"],
                "unique_together": {("value_type", "slug")},
            },
        ),
    ]
