# Generated by Django 6.0.2 on 2026-03-05 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0006_fix_label_defaults"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SocialPlatform",
            new_name="ExternalPlatform",
        ),
        migrations.AlterModelTable(
            name="externalplatform",
            table="persons_externalplatform",
        ),
    ]
