# Generated by Django 6.0.2 on 2026-03-05 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0008_seed_authority_platforms"),
    ]

    operations = [
        migrations.AddField(
            model_name="personname",
            name="confidence",
            field=models.FloatField(
                blank=True,
                help_text="Certainty score [0.0–1.0] for this name record. Null = unscored (e.g. manually entered).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="personname",
            name="provenance",
            field=models.JSONField(
                blank=True,
                help_text="Structured provenance metadata. Schema is provider-dependent. Common keys: provider (str), retrieved_at (ISO 8601 str), source_url (str), wikidata_qid (str), wikidata_alias_lang (str).",
                null=True,
            ),
        ),
    ]
