# Generated by Django 6.0.2 on 2026-03-05 21:39

import django.db.models.deletion
from django.db import migrations, models

import src.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0009_add_confidence_provenance_to_personname"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentRun",
            fields=[
                ("id", src.core.fields.ULIDField(primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("no_match", "No Match"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attributes_saved", models.PositiveIntegerField(default=0)),
                ("attributes_skipped", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(default=list)),
                ("error", models.TextField(blank=True)),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cron", "Cron"),
                            ("adjudication", "Adjudication"),
                            ("manual", "Manual"),
                            ("api", "API"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_runs",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "db_table": "persons_enrichmentrun",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "provider", "-started_at"],
                        name="persons_enr_person__375580_idx",
                    ),
                    models.Index(
                        fields=["provider", "status", "-started_at"],
                        name="persons_enr_provide_d0f0ed_idx",
                    ),
                ],
            },
        ),
    ]
