# Generated by Django 6.0.2 on 2026-03-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0010_add_enrichmentrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichmentrun",
            name="triggered_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cron", "Cron"),
                    ("adjudication", "Adjudication"),
                    ("manual", "Manual"),
                    ("api", "API"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
