# Generated by Django 6.0.2 on 2026-03-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0011_enrichmentrun_triggered_by_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentifierProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "wikidata_property_id",
                    models.CharField(
                        help_text='Wikidata property ID, e.g. "P214"', max_length=20, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier derived from English property label.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("display", models.CharField(help_text="English property label.", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="English property description."),
                ),
                (
                    "formatter_url",
                    models.CharField(
                        blank=True,
                        help_text="P1630 value. Replace $1 with the identifier value to get the URL.",
                        max_length=500,
                    ),
                ),
                (
                    "subject_item_label",
                    models.CharField(
                        blank=True,
                        help_text="English label of the P1629 subject item (the database/system).",
                        max_length=200,
                    ),
                ),
                (
                    "taxonomy_categories",
                    models.JSONField(
                        default=list,
                        help_text="List of Wikidata QIDs (P31 values) classifying this property.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When False, WikidataProvider skips this property during extraction.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked ExternalPlatform, if one exists for this identifier system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identifier_properties",
                        to="persons.externalplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Identifier Property",
                "verbose_name_plural": "External Identifier Properties",
                "db_table": "persons_externalidentifierproperty",
                "ordering": ["sort_order", "wikidata_property_id"],
            },
        ),
    ]
