# Generated by Django 6.0.2 on 2026-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0012_externalidentifierproperty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalidentifierproperty",
            name="formatter_url",
            field=models.URLField(
                blank=True,
                help_text="P1630 value. Replace $1 with the identifier value to get the URL.",
                max_length=1000,
            ),
        ),
    ]
