# Generated by Django 6.0.2 on 2026-03-06 19:25

import django.db.models.deletion
import src.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0013_alter_externalidentifierproperty_formatter_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WikidataCandidateReview",
            fields=[
                ("id", src.core.fields.ULIDField(primary_key=True, serialize=False)),
                (
                    "query_name",
                    models.CharField(
                        help_text="The name string passed to wbsearchentities.", max_length=500
                    ),
                ),
                (
                    "candidates",
                    models.JSONField(
                        help_text="List of candidate dicts, each with: qid (str), label (str), description (str), score (float), wikipedia_url (str|null), extract (str|null), properties (dict with birth_date, death_date, occupations, nationality, image_url)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("auto_linked", "Auto-Linked — Awaiting Confirmation"),
                            ("accepted", "Accepted"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected — No Match"),
                            ("skipped", "Skipped — Review Later"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "linked_qid",
                    models.CharField(
                        blank=True,
                        help_text="The accepted or auto-linked QID. Populated at creation time for auto_linked reviews; set by admin action for accepted reviews.",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wikidata_reviews",
                        to="persons.person",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wikidata_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "persons_wikidatacandidatereview",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="persons_wik_status_b6519e_idx"
                    ),
                    models.Index(
                        fields=["person", "status"], name="persons_wik_person__2f56db_idx"
                    ),
                ],
            },
        ),
    ]
