# Generated by Django 6.0.2 on 2026-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0015_seed_p2390_ballotpedia_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrichmentrun",
            name="attributes_created",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrichmentrun",
            name="attributes_refreshed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
